<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

class TaskFieldRepository extends EntityRepository
{

    /**
     * Finds all TaskFields for a given Task
     * @param $taskId
     * @return array
     */
    public function findByTask($taskId)
    {
        $query = $this->createQueryBuilder('AppBundle:TaskField field')
            ->andWhere('field.task_id = :taskId')
            ->setParameter('taskId', $taskId)
            ->orderBy('field.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Finds all the TaskFields that belong to Tasks created by a User
     * @param array $criteria
     * @param array|null $orderBy
     * @param null $limit
     * @param null $offset
     * @return array
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset); // TODO: Change the autogenerated stub
    }
}
