app:
    resource: "@AppBundle/Controller/Web"
    type:     annotation

app_api:
    resource:   "@AppApiBundle/Controller"
    type:       annotation
#    resource: '@AppApiBundle/Controller/VehicleController.php'
#    type: rest

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
