# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: masterlube_user_registration }

    utility_service:
        class: AppBundle\Service\VehicleService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    app.job.form.type:
        class: AppBundle\Form\JobFormType
        arguments:
            - '@utility_service'
        tags:
            - { name: form.type }
