# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: masterlube_user_registration }

    vehicle_service:
        class: AppBundle\Service\VehicleService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@user_service"]

    category_service:
        class: AppBundle\Service\CategoryService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    service_service:
        class: AppBundle\Service\ServiceService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@user_service"]

    task_service:
        class: AppBundle\Service\TaskService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@user_service"]

    user_service:
        class: UserBundle\Service\UserService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", '@fos_user.user_manager']

    app.category.form.type:
        class: AppBundle\Form\CategoryFormType
        arguments:
            - '@category_service'
        tags:
            - { name: form.type }

    app.service.form.type:
        class: AppBundle\Form\ServiceFormType
        arguments:
            - '@task_service'
            - '@vehicle_service'
        tags:
            - { name: form.type }

    app.task.form.type:
        class: AppBundle\Form\TaskFormType
        arguments:
            - '@category_service'
        tags:
            - { name: form.type }

    app.taskfield.form.type:
        class: AppBundle\Form\TaskFieldFormType
        arguments:
            - '@task_service'
        tags:
            - { name: form.type }

    app.vehicleinfo.form.type:
        class: AppBundle\Form\VehicleInfoFormType
        arguments:
            - '@vehicle_service'
        tags:
            - { name: form.type }
